# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/vmudrykPersonal/pre-commit-git-clang-format
    rev: 1.0.0
    hooks:
    -   id: git-clang-format
