services:
    catalog:
        image: postgres:14
        environment:
            - POSTGRES_PASSWORD=testpassword

    irods:
        build:
            context: .
            dockerfile: Dockerfile
        tty: true
        depends_on:
            - catalog
        volumes:
            - ~/Documents/iRODS/irods_client_icommands:/workspaces/icommands
            - ~/Documents/iRODS/irods:/workspaces/irods
        # The core test suite for iRODS uses SIGHUP to reload the server's configuration often.
        # To keep the iRODS Rule Language from failing and producing RE_UNABLE_TO_READ_SESSION_VAR,
        # we bump the maximum amount of shared memory from 64mb to 100mb. This is required because
        # iRODS 5 can have two Agent Factories running simultaneously (due to the SIGHUP).
        shm_size: 100mb
